### ISSUE TITLE
Were these contracts deployed on MainNet?

### ISSUE THREAD

**Issue by lock9** [neo-project/non-native-contracts#10] opened 2021-09-22 21:52 UTC
Hi,

Is it possible to call this smart contract on main net? Where can we get the hash of it? Also, where are you guys planning to store these non native contracts script hashes?
What about TestNet? What is the hash? Thanks!

**Comment by erikzhang** [comment] 2021-09-23 07:57
Duplicate of #9

**Closed as completed by erikzhang** 2021-09-23 07:57 UTC
